// This file is automatically generated by Cosmos. Add it to .gitignore and
// only edit if you know what you're doing.

import { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import './library/global.css';

import * as fixture0 from './library/components/Tooltip/Tooltip.fixture';
import * as fixture1 from './library/components/Toast/Toast.fixture';
import * as fixture2 from './library/components/Tile/Tile.fixture';
import * as fixture3 from './library/components/Tag/Tag.fixture';
import * as fixture4 from './library/components/Modal/Modal.fixture';
import * as fixture5 from './library/components/Menu/Menu.fixture';
import * as fixture6 from './library/components/Icon/Icon.fixture';
import * as fixture7 from './library/components/HTMLParser/HTMLParser.fixture';
import * as fixture8 from './library/components/Frame/Frame.fixture';
import * as fixture9 from './library/components/Form Components/TextareaGroup/TextareaGroup.fixture';
import * as fixture10 from './library/components/Form Components/SwitchGroup/SwitchGroup.fixture';
import * as fixture11 from './library/components/Form Components/SelectGroup/SelectGroup.fixture';
import * as fixture12 from './library/components/Form Components/RadioGroup/RadioGroup.fixture';
import * as fixture13 from './library/components/Form Components/Label/Label.fixture';
import * as fixture14 from './library/components/Form Components/InputGroup/InputGroup.fixture';
import * as fixture15 from './library/components/Form Components/CheckboxGroup/CheckboxGroup.fixture';
import * as fixture16 from './library/components/Drawer/Drawer.fixture';
import * as fixture17 from './library/components/Colour Tools/Colours.fixture';
import * as fixture18 from './library/components/Card/Card.fixture';
import * as fixture19 from './library/components/Button/Button.fixture';
import * as fixture20 from './library/components/Badge/Badge.fixture';

import * as decorator0 from './library/components/cosmos.decorator';

export const rendererConfig: RendererConfig = {
  "playgroundUrl": "http://localhost:5001",
  "rendererUrl": "http://localhost:4001/cosmos/<fixture>"
};

const fixtures = {
  'library/components/Tooltip/Tooltip.fixture.tsx': { module: fixture0 },
  'library/components/Toast/Toast.fixture.tsx': { module: fixture1 },
  'library/components/Tile/Tile.fixture.tsx': { module: fixture2 },
  'library/components/Tag/Tag.fixture.tsx': { module: fixture3 },
  'library/components/Modal/Modal.fixture.tsx': { module: fixture4 },
  'library/components/Menu/Menu.fixture.tsx': { module: fixture5 },
  'library/components/Icon/Icon.fixture.tsx': { module: fixture6 },
  'library/components/HTMLParser/HTMLParser.fixture.tsx': { module: fixture7 },
  'library/components/Frame/Frame.fixture.tsx': { module: fixture8 },
  'library/components/Form Components/TextareaGroup/TextareaGroup.fixture.tsx': { module: fixture9 },
  'library/components/Form Components/SwitchGroup/SwitchGroup.fixture.tsx': { module: fixture10 },
  'library/components/Form Components/SelectGroup/SelectGroup.fixture.tsx': { module: fixture11 },
  'library/components/Form Components/RadioGroup/RadioGroup.fixture.tsx': { module: fixture12 },
  'library/components/Form Components/Label/Label.fixture.tsx': { module: fixture13 },
  'library/components/Form Components/InputGroup/InputGroup.fixture.tsx': { module: fixture14 },
  'library/components/Form Components/CheckboxGroup/CheckboxGroup.fixture.tsx': { module: fixture15 },
  'library/components/Drawer/Drawer.fixture.tsx': { module: fixture16 },
  'library/components/Colour Tools/Colours.fixture.tsx': { module: fixture17 },
  'library/components/Card/Card.fixture.tsx': { module: fixture18 },
  'library/components/Button/Button.fixture.tsx': { module: fixture19 },
  'library/components/Badge/Badge.fixture.tsx': { module: fixture20 }
};

const decorators = {
  'library/components/cosmos.decorator.tsx': { module: decorator0 }
};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
